### ISSUE TITLE
Towards Transferable Adversarial Attacks with Centralized Perturbation的代码

### ISSUE THREAD

**Issue by tan-jiaqi** [spencerwooo/torchattack#14]
大佬您好，我阅读了您的论文Towards Transferable Adversarial Attacks with Centralized Perturbation，请问这篇文章的攻击方式会开源吗

**Comment by spencerwooo** [comment]
考虑开源但不是近期，因为涉及到比较复杂的项目情况，望理解。如着急进行对比试验建议优先以原文中汇报的结果为主。

**Comment by tan-jiaqi** [comment]
好的，我完全尊重您的决定，但在论文阅读时我有一些困惑，并整理成了文档发送至了您的邮箱，同时购买了爱发电，期待您的解惑。

**Comment by tan-jiaqi** [comment]
好的，我完全尊重您的决定，但在论文阅读时我有一些困惑，并整理成了文档发送至了您的gmail邮箱，同时购买了爱发电，期待您的解惑。
